### ISSUE TITLE
Customer changed information isn't updated in cookie

### ISSUE THREAD

**Issue by mattwellss** [aligent/Phoenix_VarnishCache#10]
When I update my name on `customer/account/edit`, that change isn't reflected in the cookie.

**Comment by jonpday** [comment]
@aligentjim could you please check if there is an event observer missing or changed name in newer version of Magento? thx

**Comment by mattwellss** [comment]
@jonpday This is resolved by #11, correct?

**Comment by jonpday** [comment]
correct @mattwellss thx
